language: php
dist: trusty
group: edge

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - composer cs-check
  - bin/phpstan analyse src/ --level=max -c phpstan.neon
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false
